baseurl = "https://xjtu-netverify.github.io"
title = "NetVerify"
theme = "blist"
languageCode = 'en-us'

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Net<b>Verify</b> Lab"
      introSubtitle = "@ ANTS (<b>A</b>dvanced <b>N</b>e<b>T</b>worked <b>S</b>ystem) Group in XJTU (<b>X</b>i'an <b>J</b>iao<b>t</b>ong <b>U</b>niversity)"
      news = "News"

    [[languages.en.params.about]]
      content = "We are a research lab of ANTS (Advanced NeTworked Systems) group, led by Prof. Peng Zhang."

    [[languages.en.params.about]]
      content = "Our lab focuses on the verification, simulation, and synthesis of large-scale computer networks."

    [[languages.en.params.about]]
      content = "We have proposed the data plane verifiers, APKeep (NSDI'20) and MNV (CoNEXT'23), and control plane verifiers, DNA (NSDI'22), SRE (SIGCOMM'22), and Expresso (SIGCOMM'24). Some of them are already open sourced."

    [[languages.en.params.about]]
      content = "Undergraduate students who are highly self-motivated, and interested in this research direction, are welcome to join our NetVerify lab (contact: p-zhang@xjtu.edu.cn)"

    # "We are a research lab led by Prof. Peng Zhang, focusing on Network Verification. Network verfication is an exciting new direction in computer network: it leverages formal methods, together with simulation/emulation to ensure the correctness of large and complex computer networks, e.g., datacenter networks, and wide area networks."
    # "Our lab has been working in network verifiction ever since 2015, with the work of VeriDP (CoNEXT'16). Then, we proposed data plane verifiers APKeep (NSDI'20) and MNV (CoNEXT'23). The current research focuse is control plane verification, with preliminary work like DNA (NSDI'22), SRE (SIGCOMM'22), and Expresso (SIGCOMM'24). Some of the work are already open sourced."
    # "The research group belongs to Academician Xiaohong Guan's team, and its main research directions include: future Internet, data center network; trying to mine real problems from real scenarios to improve the stability and security of China's network infrastructure; publishing academic papers with international influence, and cultivating top talents in the field of network systems."
    # "Undergraduate students who are interested in the field of systems and have self-driven are welcome to join the research group."

    # [[languages.en.menu.main]]
    #     name = "About"
    #     url = "about"
    #     weight = 1
    [[languages.en.menu.main]]
        name = "Research"
        url = "research"
        weight = 2

    [[languages.en.menu.main]]
        name = "People"
        url = "people"
        weight = 3

    [[languages.en.menu.main]]
        name = "Publications"
        url = "papers"
        # url = "https://gr.xjtu.edu.cn/en/web/p-zhang/publication"
        weight = 4

    # [[languages.en.menu.main]]
    #     name = "Courses"
    #     url = "courses"
    #     weight = 4
    #
    [[languages.en.menu.main]]
        name = "Join us"
        url = "joinus"
        # url = "/joinus/ANTS-20240509.pptx"
        weight = 5

  [languages.zh]
    contentDir = "content/zh"
    weight = 2
    languageName = "Chinese"
    [languages.zh.params]
      description = "网络验证团队"
      introTitle = "<b>网络验证团队</b>"
      introSubtitle = "西安交通大学网络系统组 @ ANTS (<b>A</b>dvanced <b>N</b>etwork <b>T</b>echnology & <b>S</b>ystem) Group in XJTU (<b>X</b>i'an <b>J</b>iao<b>t</b>ong <b>U</b>niversity)"

      news = "新闻"
      homepage.social.title = "联系我们团队"
      homepage.social.description = "如果你对我们 NetVerify 团队感兴趣，欢迎联系我们！"

    [[languages.zh.params.about]]
      content = "我们是一个由张鹏教授领导的先进网络系统（ANTS）小组研究实验室。"
    [[languages.zh.params.about]]
      content = "我们的实验室专注于大规模计算机网络的验证、模拟和合成。"
    [[languages.zh.params.about]]
      content = "我们提出了数据平面验证器 APKeep（NSDI'20）和 MNV（CoNEXT'23），以及控制平面验证器 DNA（NSDI'22）、SRE（SIGCOMM'22）和 Expresso（SIGCOMM'24）。其中一些已经开源。"
    [[languages.zh.params.about]]
      content = "欢迎自学能力强、对该研究方向感兴趣的本科生加入我们的 NetVerify 实验室（联系人：p-zhang@xjtu.edu.cn）。"

    # 网络验证是计算机网络领域一个令人兴奋的新方向：它利用形式化方法和仿真/模拟来确保大型复杂计算机网络（如数据中心网络和广域网）的正确性。
    # 自 2015 年以来，我们实验室一直致力于网络验证工作，推出了 VeriDP（CoNEXT'16）。随后，我们提出了数据平面验证器 APKeep（NSDI'20）和 MNV（CoNEXT'23）。目前的研究重点是控制平面验证，初步工作包括 DNA（NSDI'22）、SRE（SIGCOMM'22）和 Expresso（SIGCOMM'24）。其中一些工作已经开源。
    # 研究组隶属于管晓宏院士团队，主要研究方向包括：未来互联网、数据中心网络；力图从真实场景中挖掘真实问题，提高我国网络基础设施的稳定性和安全性；发表有国际影响力的学术论文，培养网络系统领域顶尖人才。
    # 欢迎对系统领域感兴趣、有自我驱动力的本科生同学加入研究组。

    # [[languages.zh.menu.main]]
    #     name = "实验室介绍"
    #     url = "about"
    #     weight = 1

    [[languages.zh.menu.main]]
        name = "研究领域"
        url = "research"
        weight = 2

    [[languages.zh.menu.main]]
        name = "团队成员"
        url = "people"
        weight = 3

    [[languages.zh.menu.main]]
        name = "论文发表"
        url = "papers"
        weight = 4

    [[languages.zh.menu.main]]
        name = "Join us"
        url = "/joinus"
        weight = 5

    # [[languages.zh.menu.main]]
    #     name = "课程信息"
    #     url = "zh/courses"
    #     weight = 4

    # [[languages.zh.menu.main]]
    #     name = "博客"
    #     url = "blog"
    #     weight = 5

[[params.introImages]]
  src = "/intro/group.jpeg"
[[params.introImages]]
  src = "/intro/group2.jpeg"
[[params.introImages]]
  src = "/intro/group3.jpeg"

# [[params.logo]]
#   src = "/logo-square-remake.png"
#   url = "/"
[[params.logo]]
  light = "/ants-logo.png"
  dark = "/ants-logo-dark.png"
  url = "/"
# [[params.logo]]
#   src = "/netverify.png"
#   url = "/"

[params]
  altLogo = "/ants-logo.png"
  altLogoDark = "/ants-logo-dark.png"
  teamLogo = "/netverify.png"
  teamLogoDark = "/netverify-dark.png"

  defaultContentLanguage = "en"
  defaultContentLanguageInSubdir = true

  enableEmoji = true
  enableRobotsTXT = true

  hasCJKLanguage = true

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  # enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  # searchKeys = [
  #   "tags",
  #   "date",
  #   "categories",
  #   "summary",
  #   "content",
  #   "link",
  #   "author"
  # ]

  # Custom copyright - optional
  copyright = "Copyright © 2024 - NetVerify Lab - ANTS Group in XJTU · All rights reserved"
  favicon = "/logo-square-remake.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "news"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true
  tocOpen = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

  joinus = true

[params.homepage.social]
  # Global params common for both languages
  title = "Contact Us"
  description = "If you are interested in our NetVerify lab in ANTS group, feel free to contact."

  [[params.homepage.social.icons]]
    website = "email"
    url = "mailto:augists@duck.com"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/XJTU-NetVerify"
  [[params.homepage.social.icons]]
    website = "logo"
    src = "/xjtu.png"
    url = "https://www.xjtu.edu.cn"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
